# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool: Linux

trigger:
- master

resources:
- repo: self
  
variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build

    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'ksv-docker-hub'
        command: 'login'
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'ksv-docker-hub'
        dockerComposeFile: 'docker-compose.yaml'
        action: 'Push services'