# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool: Linux

trigger:
- master

resources:
- repo: self
  
variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build

    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'ksv-docker-hub'
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: 'ksv-docker-hub'
        repository: 'azure-voting'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/azure-vote/Dockerfile'