# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

pool: Linux

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

steps:
- checkout: none
- task: Bash@3
  inputs:
    targetType: inline
    script: docker logs azure-vote-front -f
    
